<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.paklog.cartonization.domain.model.aggregate.CartonTest" tests="6" skipped="0" failures="1" errors="0" timestamp="2025-09-14T21:15:36" hostname="claudioeds-MacBook-Pro.local" time="0.099">
  <properties/>
  <testcase name="shouldCreateCartonSuccessfully()" classname="com.paklog.cartonization.domain.model.aggregate.CartonTest" time="0.079"/>
  <testcase name="shouldNotFitItemThatIsTooHeavy()" classname="com.paklog.cartonization.domain.model.aggregate.CartonTest" time="0.001"/>
  <testcase name="shouldNotFitItemThatIsTooLarge()" classname="com.paklog.cartonization.domain.model.aggregate.CartonTest" time="0.001"/>
  <testcase name="shouldFitItemWithinDimensions()" classname="com.paklog.cartonization.domain.model.aggregate.CartonTest" time="0.001"/>
  <testcase name="shouldDeactivateCarton()" classname="com.paklog.cartonization.domain.model.aggregate.CartonTest" time="0.013">
    <failure message="java.lang.AssertionError: &#10;Expected size: 1 but was: 2 in:&#10;[CartonCreatedEvent[cartonId=9b7d9340-e506-414e-a6ea-86498e183f9a, name=Test Box, dimensions=DimensionSet(length=12, width=8, height=6, unit=INCHES), maxWeight=Weight(value=25, unit=POUNDS), occurredOn=2025-09-14T21:15:36.258409Z],&#10;    CartonDeactivatedEvent[cartonId=9b7d9340-e506-414e-a6ea-86498e183f9a, occurredOn=2025-09-14T21:15:36.258735Z]]" type="java.lang.AssertionError">java.lang.AssertionError: 
Expected size: 1 but was: 2 in:
[CartonCreatedEvent[cartonId=9b7d9340-e506-414e-a6ea-86498e183f9a, name=Test Box, dimensions=DimensionSet(length=12, width=8, height=6, unit=INCHES), maxWeight=Weight(value=25, unit=POUNDS), occurredOn=2025-09-14T21:15:36.258409Z],
    CartonDeactivatedEvent[cartonId=9b7d9340-e506-414e-a6ea-86498e183f9a, occurredOn=2025-09-14T21:15:36.258735Z]]
	at com.paklog.cartonization.domain.model.aggregate.CartonTest.shouldDeactivateCarton(CartonTest.java:64)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</failure>
  </testcase>
  <testcase name="shouldThrowExceptionWhenCreatingCartonWithInvalidData()" classname="com.paklog.cartonization.domain.model.aggregate.CartonTest" time="0.002"/>
  <system-out><![CDATA[18:15:36.180 [Test worker] INFO  c.p.c.domain.model.aggregate.Carton - Created new carton with ID: cdc2bcad-6844-4de9-9de7-fe570b325aa1
18:15:36.255 [Test worker] INFO  c.p.c.domain.model.aggregate.Carton - Created new carton with ID: d582bdc9-f4b3-40e4-a972-51e201cf5cfa
18:15:36.256 [Test worker] INFO  c.p.c.domain.model.aggregate.Carton - Created new carton with ID: 63734608-132f-4055-82a1-0174cbeb7565
18:15:36.257 [Test worker] INFO  c.p.c.domain.model.aggregate.Carton - Created new carton with ID: 23c881d8-697b-4be6-a426-dc83302aae48
18:15:36.258 [Test worker] INFO  c.p.c.domain.model.aggregate.Carton - Created new carton with ID: 9b7d9340-e506-414e-a6ea-86498e183f9a
18:15:36.258 [Test worker] INFO  c.p.c.domain.model.aggregate.Carton - Deactivated carton: 9b7d9340-e506-414e-a6ea-86498e183f9a
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
